[package]
name = "json-fmt"
version = "0.1.0"
authors = ["vizee <vizee@live.cn>"]
edition = "2018"
license = "MIT"
description = "A cli-tool for formatting json"
repository = "https://github.com/rokumoe/jsonfmt"
readme = "README.md"

[dependencies]
